"""empty message

Revision ID: 2cb8ce9ddeb6
Revises: d74fb384c0c7
Create Date: 2021-09-15 18:14:09.964673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb8ce9ddeb6'
down_revision = 'd74fb384c0c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqllite_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userinfo',
    sa.Column('uno', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('pw', sa.String(length=200), nullable=False),
    sa.Column('n_name', sa.String(length=150), nullable=False),
    sa.Column('uimg', sa.Text(), nullable=True),
    sa.Column('number', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('uno'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('prefer_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uno', sa.Integer(), nullable=False),
    sa.Column('mno', sa.Integer(), nullable=False),
    sa.Column('mpref', sa.Integer(), nullable=True),
    sa.Column('mwish', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mno'], ['movieinfo.mno'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uno'], ['userinfo.uno'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('userInfo')
    op.drop_table('sqlite_sequence')
    op.drop_table('preferMovie')
    with op.batch_alter_table('movieinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie', sa.Text(), nullable=True))
        batch_op.alter_column('mno',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movieinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.TEXT(), nullable=True))
        batch_op.alter_column('mno',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('movie')

    op.create_table('preferMovie',
    sa.Column('uno', sa.INTEGER(), nullable=False),
    sa.Column('mno', sa.INTEGER(), nullable=False),
    sa.Column('mpref', sa.INTEGER(), nullable=True),
    sa.Column('mwish', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['mno'], ['movieinfo.mno'], ),
    sa.ForeignKeyConstraint(['uno'], ['userInfo.uno'], )
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.create_table('userInfo',
    sa.Column('uno', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('pw', sa.TEXT(), nullable=False),
    sa.Column('n_name', sa.TEXT(), nullable=False),
    sa.Column('uimg', sa.BLOB(), nullable=True),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('uno')
    )
    op.drop_table('prefer_movie')
    op.drop_table('userinfo')
    op.drop_table('sqllite_sequence')
    # ### end Alembic commands ###
