"""empty message

Revision ID: 54965954b719
Revises: b4fba3c4f557
Create Date: 2021-09-28 18:35:53.742380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54965954b719'
down_revision = 'b4fba3c4f557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefer_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uno', sa.Integer(), nullable=False),
    sa.Column('mno', sa.Integer(), nullable=False),
    sa.Column('mpref', sa.Integer(), nullable=True),
    sa.Column('mwish', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mno'], ['movieinfo.mno'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uno'], ['userInfo.uno'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('preferMovie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferMovie',
    sa.Column('uno', sa.INTEGER(), nullable=False),
    sa.Column('mno', sa.INTEGER(), nullable=False),
    sa.Column('mpref', sa.INTEGER(), nullable=True),
    sa.Column('mwish', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['mno'], ['movieinfo.mno'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uno'], ['userInfo.uno'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uno', 'mno')
    )
    op.drop_table('prefer_movie')
    # ### end Alembic commands ###
