"""empty message

Revision ID: 896425606cf9
Revises: 6e56e0f5be7d
Create Date: 2021-09-09 13:38:09.178614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896425606cf9'
down_revision = '6e56e0f5be7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_no', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('user_name', sa.String(length=150), nullable=False),
    sa.Column('user_phone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_no'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
