"""empty message

Revision ID: 318eeb754153
Revises: 4b5085f77bc3
Create Date: 2021-09-11 16:16:20.487272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318eeb754153'
down_revision = '4b5085f77bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_genre', sa.String(length=200), nullable=True))
        batch_op.drop_column('movie_genre2')
        batch_op.drop_column('movie_genre1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_genre1', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('movie_genre2', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('movie_genre')

    # ### end Alembic commands ###
