"""empty message

Revision ID: 4b5085f77bc3
Revises: 6e96938e1424
Create Date: 2021-09-11 11:12:22.661967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5085f77bc3'
down_revision = '6e96938e1424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('movie_no', sa.Integer(), nullable=False),
    sa.Column('movie_title', sa.String(length=200), nullable=False),
    sa.Column('movie_image', sa.LargeBinary(), nullable=True),
    sa.Column('movie_actor', sa.Text(), nullable=True),
    sa.Column('movie_year', sa.Integer(), nullable=True),
    sa.Column('movie_age', sa.String(length=150), nullable=True),
    sa.Column('movie_time', sa.String(length=150), nullable=True),
    sa.Column('movie_story', sa.Text(), nullable=True),
    sa.Column('movie_genre1', sa.String(length=200), nullable=True),
    sa.Column('movie_genre2', sa.String(length=200), nullable=True),
    sa.Column('movie_keyword', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('movie_no', name=op.f('pk_movie'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
